### PR TITLE
layers/meta-opentrons: save logs on disk

### PR DESCRIPTION
**Pull request by sfoster1**
We previously had storage on auto but didn't have a /var/logs/journal so logs were going only to RAM with a limit of 64 megs. Now we'll make the directory and store 4G of logs.

### CODE REVIEW

**Review by Laura-Danielle — APPROVED** [review]
nice

**Review by ahiuchingau — APPROVED** [review]
🙏

**Comment by sfoster1** [comment]
```
cat mount/lib/systemd/journald.conf.d/01-storage.conf
[Journal]
Storage=persistent
ForwardToSyslog=yes
```
it (finally) works with the explicit recipe override

**Comment by vegano1** [comment]
I was concerned about the 4GB max journal size this will take up, but by default, it's either 15% of the total filesystem space OR 4GB. Since this is in the userfs partition it will be fine.

**Pull request merged**
