### PR TITLE
opentrons-mcu-firmware: use manifest from install

### PR DESCRIPTION
**Pull request by sfoster1**
The firmware repo now builds the manifest on its own, during --install, so just use that.

Requires https://github.com/Opentrons/ot3-firmware/pull/573

### CODE REVIEW

**Review by Laura-Danielle — APPROVED** [review]
nice

**Comment by sfoster1** [comment]
Build succeeded: https://ot3-development.builds.opentrons.com/ot3-oe/4167204789/ot3-system.zip
https://github.com/Opentrons/oe-core/actions/runs/4167204789

**Comment by sfoster1** [comment]
Oh it didn't actually get the manifest though.

**Comment by sfoster1** [comment]
Ok after some further updates https://github.com/Opentrons/oe-core/actions/runs/4175888607/jobs/7231423955 ( system zip: https://ot3-development.builds.opentrons.com/ot3-oe/4175342073/ot3-system.zip ) now actually contains everything!

**Review by fsinapi — APPROVED** [review]

**Review by vegano1 — APPROVED** [review]

**Comment by vegano1** [comment]
Very nice, this is much cleaner!

**Comment by sfoster1** [comment]
And it works!

**Pull request merged**
